title: Ishaan Shah
url: "/"
baseurl: ""

markdown: kramdown

tracking_id: "G-GM3STVD4HN"

footer: yes
footer_text: "© Copyright 2026 Ishaan Shah."

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Publications"
   link: "/publications"
 - name: "Projects"
   link: "/projects"
 - name: "Pics"
   link: "/pics"
#  - name: "Notes"
#    link: "/notes"
 - name: "Resume"
   link: "/resume.pdf"

collections:
  pics:
    output: true
    permalink: /pics/:name/

twitter_username: "ishaan_n_shah"
