title: Ishaan Shah
url: "https://ishaanshah.github.io"
baseurl: ""

markdown: kramdown

tracking_id: #

footer: yes
footer_text: "© Copyright 2022 Ishaan Shah."

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Projects"
   link: "/projects"
 - name: "Publications"
   link: "/publications"
 - name: "Resume"
   link: "/resume.pdf"

twitter_username: "ishaan_n_shah"
