title: Ishaan Shah
url: "/"
baseurl: ""

markdown: kramdown

tracking_id: "G-GM3STVD4HN"

footer: yes
footer_text: "© Copyright 2024 Ishaan Shah."

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Publications"
   link: "/publications"
 - name: "Projects"
   link: "/projects"
#  - name: "Notes"
#    link: "/notes"
 - name: "Resume"
   link: "/resume.pdf"

twitter_username: "ishaan_n_shah"
